sonar.projectKey=cocomhub_cocom
sonar.organization=cocomhub
sonar.host.url=https://sonarcloud.io
sonar.go.coverage.reportPaths=build/cover.out
sonar.test.exclusions=tests/e2e/**
sonar.sourceEncoding=UTF-8
sonar.sources=.,cmd/,internal/,pkg/
sonar.exclusions=tests/**,build/**,tools/**,node_modules/**
